---
namespace: "{{ lookup('env','NAMESPACE') | default('mariadb-apb', true) }}"
mysql_password: "{{ lookup('mysql_password', '/tmp/pass chars=ascii_letters,digits') }}"
mysql_root_password: "{{ lookup('mysql_root_password', '/tmp/rootpass chars=ascii_letters,digits') }}"
mysql_user: "{{ lookup('env','MYSQL_USER') | default('admin', true) }}"
mariadb_volume_size: "1Gi"
mariadb_version: "{{ lookup('env','MARIADB_VERSION') | default('10.0', true) }}"
