---
namespace: "{{ lookup('env','NAMESPACE') | default('nextcloud', true) }}"
mysql_name: "{{ lookup('env','MYSQL_DATABASE') | default('nextcloud', true) }}"
mysql_user: "{{ lookup('env','MYSQL_USER') | default('nextcloud', true) }}"
mysql_password: "{{ lookup('env','MYSQL_PASSWORD') | default('admin', true) }}"
mysql_root_password: "{{ lookup('env','MYSQL_ROOT_PASSWORD') | default('admin', true) }}"
mysql_host: "{{ lookup('env','MYSQL_HOST') | default('mysql', true) }}"
nextcloud_version: "{{ lookup('env','NEXTCLOUD_VERSION') | default('latest', true) }}"
mysql_version: "{{ lookup('env','MYSQL_VERSION') | default('latest', true) }}"
admin_user: "{{ lookup('env','ADMIN_USER') | default('admin', true) }}"
admin_password: "{{ lookup('env','ADMIN_PASSWORD') | default('admin', true) }}"
domain: "{{ lookup('env','DOMAIN') | default('localhost', true) }}"
db_type: "{{ lookup('env','DB_TYPE') | default('mysql', true) }}"

persistent_volume_claims:
  - name: nextcloud-data
    size: 3Ti
    access_modes:
      - ReadWriteMany
    match_labels:
      app: nextcloud
      pod: nextcloud-data
      env: '{{ env | default("test") }}'
  - name: nextcloud-media
    size: 3Ti
    access_modes:
      - ReadWriteMany
    match_labels:
      app: nextcloud
      pod: nextcloud-media
      env: '{{ env | default("test") }}'
  - name: nextcloud-apps2
    size: 20Gi
    access_modes:
      - ReadWriteMany
    match_labels:
      app: nextcloud
      pod: nextcloud-apps2
      env: '{{ env | default("test") }}'
  - name: nextcloud-themes
    size: 20Gi
    access_modes:
      - ReadWriteMany
    match_labels:
      app: nextcloud
      pod: nextcloud-themes
      env: '{{ env | default("test") }}'
  - name: mysql-storage
    size: 20Gi
    access_modes:
      - ReadWriteOnce
    match_labels:
      app: nextcloud
      pod: mysql-storage
      env: '{{ env | default("test") }}'
  - name: mysql-logs
    size: 20Gi
    access_modes:
      - ReadWriteOnce
    match_labels:
      app: nextcloud
      pod: mysql-logs
      env: '{{ env | default("test") }}'
  - name: redis-data
    size: 20Gi
    access_modes:
      - ReadWriteOnce
    match_labels:
      app: nextcloud
      pod: redis-data
      env: '{{ env | default("test") }}'
  - name: solr-data
    size: 20Gi
    access_modes:
      - ReadWriteOnce
    match_labels:
      app: nextcloud
      pod: solr-data
      env: '{{ env | default("test") }}'
  - name: nginx-proxy-certs
    size: 1Gi
    access_modes:
      - ReadWriteOnce
    match_labels:
      app: nextcloud
      pod: nginx-proxy-certs
      env: '{{ env | default("test") }}'