---
namespace: "{{ lookup('env','NAMESPACE') | default('plex', true) }}"

persistent_volume_claims:
  - name: plex-config
    size: 10Gi
    access_modes:
      - ReadWriteOnce
    match_labels:
      app: plex
      pod: plex-config
      env: '{{ env | default("test") }}'
  - name: plex-data
    size: 10Ti
    access_modes:
      - ReadWriteOnce
    match_labels:
      app: plex
      pod: plex-data
      env: '{{ env | default("test") }}'