---
namespace: "{{ lookup('env','NAMESPACE') | default('mysql-apb', true) }}"
mysql_password: "{{ lookup('mysql_password', '/tmp/pass chars=ascii_letters,digits') }}"
mysql_root_password: "{{ lookup('mysql_root_password', '/tmp/rootpass chars=ascii_letters,digits') }}"
mysql_user: "{{ lookup('env','MYSQL_USER') | default('admin', true) }}"
mysql_volume_size: "1Gi"
mysql_version: "{{ lookup('env','MYSQL_VERSION') | default('5.7', true) }}"
